version: '3.8'

services:
  webapi:
    image: coffee-sharp-webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=CoffeeSharpDb;Username=postgres;Password=yourpassword
      - ConnectionStrings__LogDbConnection=Host=logdb;Port=5432;Database=CoffeeSharpLogs;Username=postgres;Password=yourpassword
    depends_on:
      - db
      - logdb

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: CoffeeSharpDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  logdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: CoffeeSharpLogs
    ports:
      - "5433:5432"
    volumes:
      - postgres_logs_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_logs_data:
