version: '3.8'

services:
  webapi:
    image: coffee-sharp-webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=CoffeeSharpDb;Username=postgres;Password=yourpassword
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: CoffeeSharpDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: